spring.application.name=rentwise-backend
spring.datasource.url=jdbc:postgresql://ep-nameless-voice-a1zn79oa-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_fOrMLbYS4AW7&sslmode=require&channelBinding=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_fOrMLbYS4AW7
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.driverClassName=org.h2.Driver
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#npg_fOrMLbYS4AW7@
#postgresql://neondb_owner:npg_fOrMLbYS4AW7@ep-nameless-voice-a1zn79oa-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require